package com.nutrino.aichatbot.domain.model.askQuestion

/**
 * Represents the request that the domain layer sends when asking Gemini a question.
 *
 * This is a domain-only model, so it does not carry serialization annotations or any
 * dependency on the remote DTO package. The repository maps this model to the API request
 * format before it is sent over the network.
 *
 * @property contents The list of message contents that make up the request. In this app,
 * this usually contains a single user message with one text part, but the type stays open
 * enough to support richer request bodies later.
 */
data class AskQuestionRequest(
    val contents: List<Content?>?
)

/**
 * Represents the response returned to the domain layer after Gemini generates a reply.
 *
 * The model mirrors the remote response shape closely so the presentation layer can inspect
 * the candidates, response metadata, and token usage without importing the remote DTO types.
 *
 * @property candidates The list of candidate responses generated by Gemini.
 * @property modelVersion The model version reported by the API, if available.
 * @property responseId The unique response identifier returned by the API, if available.
 * @property usageMetadata Token and usage statistics that describe how the response was produced.
 */
data class AskQuestionResponse(
    val candidates: List<Candidate>?,
    val modelVersion: String?,
    val responseId: String?,
    val usageMetadata: UsageMetadata?
)

/**
 * Represents a top-level content block in the request payload.
 *
 * The request may contain one or more content entries depending on how the prompt is built.
 * Each content item usually wraps one or more parts.
 *
 * @property parts The text or structured parts that make up the content block.
 */
data class Content(
    val parts: List<Part?>?
)

/**
 * Represents one candidate response returned by Gemini.
 *
 * Each candidate can contain its own content, finish reason, and index. The UI usually reads
 * the first candidate, but keeping the full structure available makes the domain model future-proof.
 *
 * @property content The generated content for this candidate.
 * @property finishReason The reason the model stopped generating, if supplied by the API.
 * @property index The candidate index within the response.
 */
data class Candidate(
    val content: ContentX?,
    val finishReason: String?,
    val index: Int?
)

/**
 * Represents the generated content block inside a response candidate.
 *
 * The response uses a slightly different content type than the request because the generated
 * output may contain richer metadata, including role information and thought signatures.
 *
 * @property parts The generated parts for this candidate.
 * @property role The role attached to the generated content, if provided.
 */
data class ContentX(
    val parts: List<PartX>?,
    val role: String?
)

/**
 * Represents a simple text part used in the request payload.
 *
 * @property text The user prompt text or any other text segment included in the request.
 */
data class Part(
    val text: String?
)

/**
 * Represents a generated text part returned in the response payload.
 *
 * @property text The generated text segment.
 * @property thoughtSignature An optional signature attached by the model for reasoning metadata.
 */
data class PartX(
    val text: String?,
    val thoughtSignature: String?
)

/**
 * Represents token and usage statistics for a Gemini response.
 *
 * These fields are useful for debugging, monitoring usage, and understanding how much prompt
 * and output content contributed to the final response.
 *
 * @property candidatesTokenCount The number of tokens consumed by candidate outputs, if known.
 * @property promptTokenCount The number of tokens in the prompt, if known.
 * @property promptTokensDetails A more detailed breakdown of prompt token usage.
 * @property thoughtsTokenCount The number of thought tokens used, if reported.
 * @property totalTokenCount The total number of tokens counted for the request/response pair.
 */
data class UsageMetadata(
    val candidatesTokenCount: Int?,
    val promptTokenCount: Int?,
    val promptTokensDetails: List<PromptTokensDetail?>?,
    val thoughtsTokenCount: Int?,
    val totalTokenCount: Int?
)

/**
 * Describes a per-modality token breakdown within the request metadata.
 *
 * @property modality The modality that the token count belongs to, such as text.
 * @property tokenCount The number of tokens counted for the modality.
 */
data class PromptTokensDetail(
    val modality: String?,
    val tokenCount: Int?
)
